# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-07 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
